config/routes.rb
#==============================================================================
# Copyright (C) 2024-present Alces Flight Ltd.
#
# This file is part of Concertim Visualisation App.
#
# This program and the accompanying materials are made available under
# the terms of the Eclipse Public License 2.0 which is available at
# <https://www.eclipse.org/legal/epl-2.0>, or alternative license
# terms made available by Alces Flight Ltd - please direct inquiries
# about licensing to licensing@alces-flight.com.
#
# Concertim Visualisation App is distributed in the hope that it will be useful, but
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR
# IMPLIED INCLUDING, WITHOUT LIMITATION, ANY WARRANTIES OR CONDITIONS
# OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A
# PARTICULAR PURPOSE. See the Eclipse Public License 2.0 for more
# details.
#
# You should have received a copy of the Eclipse Public License 2.0
# along with Concertim Visualisation App. If not, see:
#
#  https://opensource.org/licenses/EPL-2.0
#
# For more information on Concertim Visualisation App, please visit:
# https://github.com/openflighthpc/concertim-ct-visualisation-app
#==============================================================================

Rails.application.routes.draw do
  # Engines
  authenticate :user, ->(user) { user.root? } do
    mount GoodJob::Engine => 'good_job'
  end

  devise_for :users,
    only: [:sessions, :registrations],
    controllers: { sessions: "sessions", registrations: "registrations" },
    path: 'accounts'
  # Add "/users/sign_in" route to avoid breaking API clients.
  devise_scope :user do
    post "users/sign_in", to: "sessions#create"
  end

  mount ActionCable.server => '/cable'

  # We need to redirect here, otherwise the devise redirections will take us to
  # the legacy sign up page.
  root to: redirect('/racks')

  resource :interactive_rack_views, only: [], path: '/irv' do
    get :configuration
  end

  resource :interactive_rack_views, only: :show, path: '/racks'
  resources :racks, only: [:show] do
    member do
      get :devices
      get 'instructions/:instruction_id', to: 'racks#instructions', as: :instructions
    end
  end

  scope '/cloud-env' do
    resource :cloud_service_config, path: '/config' do
      member do
        post :send_config, as: 'send', path: 'send'
      end
    end
    resources :cluster_types, path: 'cluster-types', only: [:index], param: :foreign_id do
      resources :clusters, only: [:new, :create]
    end
  end

  scope '/compute-unit-usage' do
    get '/cluster-types', to: 'cluster_types#admin_index', as: :admin_cluster_type_index
    get '/instance-types', to: 'templates#index', as: :templates
    get '/volumes', to: 'settings#edit_volume_settings', as: :edit_volume_settings
  end

  resources :cluster_types, only: [:edit, :update]

  resources :users, only: [:index, :edit, :update, :destroy]

  resource :settings, only: [:edit, :update]

  get '/statistics', to: 'statistics#index'

  resources :teams do
    member do
      get :usage_limits
    end
    resources :team_roles, only: [:index, :new, :create]
    resources :compute_unit_deposits, only: [:new, :create, :index]
  end

  resources :compute_unit_deposits, only: [:edit, :update, :destroy]
  resources :team_roles, only: [:edit, :update, :destroy]

  resources :key_pairs, only: [:index, :new, :create] do
    collection do
      get '/success', to: 'key_pairs#success'
      delete '/:name', to: 'key_pairs#destroy', as: :delete
    end
  end

  resources :devices, only: [:show] do
    resources :metrics, only: [:index]
  end

  resources :templates, only: [:edit, :update]

  # API routes
  #
  # Some of these have been done in a non-railsy way (you have "posts" where you should have 
  # "puts", missing plurals where we should have plurals... to be tidied up at some point.
  #
  namespace :api do
    ['v1'].each do |version|
      namespace version do

        resources :racks
        resources :templates, only: [:index, :create, :update, :destroy]
        resources :nodes, only: [:create]
        resources :devices, only: [:index, :show, :update, :destroy] do
          resources :metrics, :constraints => { :id => /.*/ }, only: [:show]
        end
        resources :data_source_maps, path: 'data-source-maps', only: [:index]
        resources :teams, only: [:index, :create, :update, :destroy]

        # For use by the interactive rack view
        namespace :irv do
          resources :racks, only: [:index] do
            member do
              post :request_status_change
            end
            collection do 
              get :modified
            end
          end
          resources :nonrack_devices, only: [:index] do
            collection do
              get :modified
            end
          end
          resources :chassis do
            member do
              post :update_position
            end
          end
          resources :devices, only: [] do
            member do
              post :update_slot
              post :request_status_change
            end
          end
          resources :rackview_presets, only: [:index, :create, :update, :destroy]
          resources :metrics, :constraints => { :id => /.*/ }, only: [] do
            member do
              post :show
            end
          end
        end

        resources :metrics, :constraints => { :id => /.*/ }, only: [] do
          get :structure, :on => :collection
        end
        resources :users, only: [:index, :update, :destroy] do
          collection do
            # Endpoint for checking user abilities.
            get :permissions, action: :permissions, as: :permissions
            # Endpoint for getting the currently signed in user.
            get :current
          end
        end
      end
    end
  end
end

app/controllers/cluster_types_controller.rb
#==============================================================================
# Copyright (C) 2024-present Alces Flight Ltd.
#
# This file is part of Concertim Visualisation App.
#
# This program and the accompanying materials are made available under
# the terms of the Eclipse Public License 2.0 which is available at
# <https://www.eclipse.org/legal/epl-2.0>, or alternative license
# terms made available by Alces Flight Ltd - please direct inquiries
# about licensing to licensing@alces-flight.com.
#
# Concertim Visualisation App is distributed in the hope that it will be useful, but
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR
# IMPLIED INCLUDING, WITHOUT LIMITATION, ANY WARRANTIES OR CONDITIONS
# OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A
# PARTICULAR PURPOSE. See the Eclipse Public License 2.0 for more
# details.
#
# You should have received a copy of the Eclipse Public License 2.0
# along with Concertim Visualisation App. If not, see:
#
#  https://opensource.org/licenses/EPL-2.0
#
# For more information on Concertim Visualisation App, please visit:
# https://github.com/openflighthpc/concertim-ct-visualisation-app
#==============================================================================

class ClusterTypesController < ApplicationController
  include ControllerConcerns::ResourceTable
  load_and_authorize_resource :cluster_type, class: ClusterType
  before_action :get_types, except: [:edit, :update]

  def index
    @cluster_types = @cluster_types.where.not(base_compute_units: nil)
    @valid_teams = current_user.teams_where_admin.select(&:meets_cluster_compute_unit_requirement?)
    @unavailable_teams =  current_user.teams.where.not(id: @valid_teams.pluck(:id))
    @all_teams = current_user.teams.reorder(:name)
    @team = Team.find(params[:team_id]) if params[:team_id]
  end

  def admin_index
    @cluster_types = resource_table_collection(@cluster_types)
  end

  def edit
  end

  def update
    if @cluster_type.update(cluster_type_params)
      flash[:info] = "Successfully updated cluster type compute_units"
      redirect_to admin_cluster_type_index_path
    else
      flash[:alert] = "Unable to update cluster type: #{@cluster_type.errors.full_messages.join("; ")}"
      render action: :edit
    end
  end

  private

  def get_types
    @cloud_service_config = CloudServiceConfig.first
    if @cloud_service_config
      use_cache = params[:use_cache] != "false"
      result = SyncAllClusterTypesJob.perform_now(@cloud_service_config, use_cache)
      flash.now.alert = result.error_message unless result.success?
    end
    @cluster_types = @cluster_types.reorder(:order, :id)
  end

  PERMITTED_PARAMS = %w[base_compute_units]
  def cluster_type_params
    params.require(:cluster_type).permit(*PERMITTED_PARAMS)
  end
end

app/views/cluster_types/_card.html.erb
<% cluster_type = card %>
<% disabled = true %>
<% if team %>
  <% cluster = Cluster.new(cluster_type: cluster_type, team: team) %>
  <% if current_user.can?(:create, cluster) %>
    <% disabled = false %>
    <%  title = "" %>
  <% else %>
    <% title =  if team.meets_cluster_compute_unit_requirement?
                  "You do not have permission to create clusters"
                else
                  "Insufficient compute_units. Your chosen team must have at least #{Rails.application.config.cluster_compute_unit_requirement} compute_units to create a cluster"
                end
    %>
  <% end %>
<% else %>
  <% title = if !current_user.can?(:create, Cluster)
               "You do not have permission to create this cluster"
             elsif !available_teams
               "Unable to create a cluster - you must be admin for a team with at least #{Rails.application.config.cluster_compute_unit_requirement} compute_units to create a cluster"
             else
               "Please select a team"
             end
  %>
<% end %>
<%= link_to( disabled ? "#" : new_cluster_type_cluster_path(cluster_type, team_id: team&.id),
             { class: "cluster-type-card #{"disabled-cluster-type-card" if disabled }", title: title,
               data: { base_target_url: new_cluster_type_cluster_path(cluster_type) } }) do %>
  <%= render partial: 'card_content', object: cluster_type %>
<% end %>

app/views/cluster_types/_card_content.html.erb
<% cluster_type = card_content %>

<h2 class="cluster-type-card-title"><%= cluster_type.name %></h2>
<% if cluster_type.logo_url.present? %>
  <%= image_tag cluster_type.logo_url, class: "cluster-type-card-icon" %>
<% end %>
<span class="cluster-type-card-description"><%= cluster_type.description %></span>

app/views/cluster_types/admin_index.html.erb
<% set_title "Manage compute unit usage calculations" -%>

<%= render partial: 'settings/tabbar' %>

<%= render_tab_content do %>
  <%= render_resource_table_for @cluster_types, searchable: true do |t| %>
    <% t.on_empty_collection do %>
      <% capture do %>
        No cluster types have been found.
      <% end %>
    <% end %>

    <% t.attribute_column :id, sortable: true %>
    <% t.attribute_column :name, sortable: true %>
    <% t.attribute_column :foreign_id, sortable: true, title: "Cluster Builder ID" %>
    <% t.attribute_column :foreign_id, sortable: true, title: "Cluster Builder ID" %>
    <% t.attribute_column :description %>
    <% t.attribute_column :base_compute_units, sortable: true, title: "Base Compute Unit Usage" %>

    <% t.actions_column do |actions, cluster_type| %>
      <% actions.add_with_auth can: :edit, on: cluster_type, text: 'Edit base compute units', path: edit_cluster_type_path(cluster_type.id) %>
    <% end %>
  <% end %>
<% end %>

app/views/cluster_types/edit.html.erb
<%
  set_title "Edit compute unit allocation for cluster type #{@cluster_type.name}"
-%>

<%= simple_form_for @cluster_type, url: cluster_type_path(@cluster_type.id), html: { class: 'no_border' } do |f| %>
  <%= f.input :base_compute_units, label: "Base compute unit allocation",
              hint: "Hourly compute unit allocation for clusters of this type, excluding instances and volumes",
              input_html: { min: 0, step: 1 }
  %>
  <%= f.button :submit %>
<% end %>

app/views/cluster_types/index.html.erb
<% set_title "Create cluster - select cluster type" %>
<% content_for(:head) do %>
  <%= javascript_import_module_tag "cluster_types/index" %>
<% end %>

<div class="text-center">
  <h3>
  Choose from our selection of cluster types to start building a cluster using
  your private cloud resources.
  </h3>
</div>

<% if @cloud_service_config.nil? %>
   <p>
     New clusters cannot be launched as the Cloud Environment has not yet been configured.
     <% if current_user.root %>
       Please <%= link_to 'set the configuration', cloud_service_config_path %> to continue.
     <% else %>
      Please contact an admin.
     <% end %>
   </p>
<% elsif @cluster_types.empty? %>
  <p>There are no cluster types available at present.</p>
<% else %>
  <div class="new_cluster choose-team">
    <% if @valid_teams.any? %>
      <div class="formItem">
        <div class="field">
          <%= label_tag :team_id, "Team", class: "required_field" %>
          <select id="choose_cluster_team" name="team_id" required <% "disabled" unless current_user.can?(:create, Cluster) %>>
            <option value="" disabled selected>Select Team</option>
            <% @all_teams.each do |team| %>
              <% disabled = @unavailable_teams.include?(team) ? 'disabled' : '' %>
              <option value="<%= team.id %>" <%= 'selected' if @team && @team.id == team.id %> <%= disabled %>>
                <%= team.name %>
              </option>
            <% end %>
          </select>
        </div>
        <div class="constraint-text">
          You must be a team admin and the team have at least <%= Rails.application.config.cluster_compute_unit_requirement %> compute_units
        </div>
      </div>
    <% else %>
      <p>
        You must be an admin for a team with at least <%= Rails.application.config.cluster_compute_unit_requirement %> compute_units to create a cluster.
      </p>
    <% end %>
  </div>

  <div class="cluster-types-card-deck">
    <% available_teams = @valid_teams.any? %>
    <% @cluster_types.each do |cluster_type| %>
      <%= render partial: 'card', object: cluster_type, locals: { team: @team, available_teams: available_teams } %>
    <% end %>
  </div>
<% end %>