config/routes.rb
#==============================================================================
# Copyright (C) 2024-present Alces Flight Ltd.
#
# This file is part of Concertim Visualisation App.
#
# This program and the accompanying materials are made available under
# the terms of the Eclipse Public License 2.0 which is available at
# <https://www.eclipse.org/legal/epl-2.0>, or alternative license
# terms made available by Alces Flight Ltd - please direct inquiries
# about licensing to licensing@alces-flight.com.
#
# Concertim Visualisation App is distributed in the hope that it will be useful, but
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR
# IMPLIED INCLUDING, WITHOUT LIMITATION, ANY WARRANTIES OR CONDITIONS
# OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A
# PARTICULAR PURPOSE. See the Eclipse Public License 2.0 for more
# details.
#
# You should have received a copy of the Eclipse Public License 2.0
# along with Concertim Visualisation App. If not, see:
#
#  https://opensource.org/licenses/EPL-2.0
#
# For more information on Concertim Visualisation App, please visit:
# https://github.com/openflighthpc/concertim-ct-visualisation-app
#==============================================================================

Rails.application.routes.draw do
  # Engines
  authenticate :user, ->(user) { user.root? } do
    mount GoodJob::Engine => 'good_job'
  end

  devise_for :users,
    only: [:sessions, :registrations],
    controllers: { sessions: "sessions", registrations: "registrations" },
    path: 'accounts'
  # Add "/users/sign_in" route to avoid breaking API clients.
  devise_scope :user do
    post "users/sign_in", to: "sessions#create"
  end

  mount ActionCable.server => '/cable'

  # We need to redirect here, otherwise the devise redirections will take us to
  # the legacy sign up page.
  root to: redirect('/racks')

  resource :interactive_rack_views, only: [], path: '/irv' do
    get :configuration
  end

  resource :interactive_rack_views, only: :show, path: '/racks'
  resources :racks, only: [:show] do
    member do
      get :devices
      get 'instructions/:instruction_id', to: 'racks#instructions', as: :instructions
    end
  end

  scope '/cloud-env' do
    resource :cloud_service_config, path: '/config' do
      member do
        post :send_config, as: 'send', path: 'send'
      end
    end
    resources :cluster_types, path: 'cluster-types', only: [:index], param: :foreign_id do
      resources :clusters, only: [:new, :create]
    end
  end

  scope '/compute-unit-usage' do
    get '/cluster-types', to: 'cluster_types#admin_index', as: :admin_cluster_type_index
    get '/instance-types', to: 'templates#index', as: :templates
    get '/volumes', to: 'settings#edit_volume_settings', as: :edit_volume_settings
  end

  resources :cluster_types, only: [:edit, :update]

  resources :users, only: [:index, :edit, :update, :destroy]

  resource :settings, only: [:edit, :update]

  get '/statistics', to: 'statistics#index'

  resources :teams do
    member do
      get :usage_limits
    end
    resources :team_roles, only: [:index, :new, :create]
    resources :compute_unit_deposits, only: [:new, :create, :index]
  end

  resources :compute_unit_deposits, only: [:edit, :update, :destroy]
  resources :team_roles, only: [:edit, :update, :destroy]

  resources :key_pairs, only: [:index, :new, :create] do
    collection do
      get '/success', to: 'key_pairs#success'
      delete '/:name', to: 'key_pairs#destroy', as: :delete
    end
  end

  resources :devices, only: [:show] do
    resources :metrics, only: [:index]
  end

  resources :templates, only: [:edit, :update]

  # API routes
  #
  # Some of these have been done in a non-railsy way (you have "posts" where you should have 
  # "puts", missing plurals where we should have plurals... to be tidied up at some point.
  #
  namespace :api do
    ['v1'].each do |version|
      namespace version do

        resources :racks
        resources :templates, only: [:index, :create, :update, :destroy]
        resources :nodes, only: [:create]
        resources :devices, only: [:index, :show, :update, :destroy] do
          resources :metrics, :constraints => { :id => /.*/ }, only: [:show]
        end
        resources :data_source_maps, path: 'data-source-maps', only: [:index]
        resources :teams, only: [:index, :create, :update, :destroy]

        # For use by the interactive rack view
        namespace :irv do
          resources :racks, only: [:index] do
            member do
              post :request_status_change
            end
            collection do 
              get :modified
            end
          end
          resources :nonrack_devices, only: [:index] do
            collection do
              get :modified
            end
          end
          resources :chassis do
            member do
              post :update_position
            end
          end
          resources :devices, only: [] do
            member do
              post :update_slot
              post :request_status_change
            end
          end
          resources :rackview_presets, only: [:index, :create, :update, :destroy]
          resources :metrics, :constraints => { :id => /.*/ }, only: [] do
            member do
              post :show
            end
          end
        end

        resources :metrics, :constraints => { :id => /.*/ }, only: [] do
          get :structure, :on => :collection
        end
        resources :users, only: [:index, :update, :destroy] do
          collection do
            # Endpoint for checking user abilities.
            get :permissions, action: :permissions, as: :permissions
            # Endpoint for getting the currently signed in user.
            get :current
          end
        end
      end
    end
  end
end

app/models/key_pair.rb
#==============================================================================
# Copyright (C) 2024-present Alces Flight Ltd.
#
# This file is part of Concertim Visualisation App.
#
# This program and the accompanying materials are made available under
# the terms of the Eclipse Public License 2.0 which is available at
# <https://www.eclipse.org/legal/epl-2.0>, or alternative license
# terms made available by Alces Flight Ltd - please direct inquiries
# about licensing to licensing@alces-flight.com.
#
# Concertim Visualisation App is distributed in the hope that it will be useful, but
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR
# IMPLIED INCLUDING, WITHOUT LIMITATION, ANY WARRANTIES OR CONDITIONS
# OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A
# PARTICULAR PURPOSE. See the Eclipse Public License 2.0 for more
# details.
#
# You should have received a copy of the Eclipse Public License 2.0
# along with Concertim Visualisation App. If not, see:
#
#  https://opensource.org/licenses/EPL-2.0
#
# For more information on Concertim Visualisation App, please visit:
# https://github.com/openflighthpc/concertim-ct-visualisation-app
#==============================================================================

class KeyPair
  include ActiveModel::API

  ############################
  #
  # Validations
  #
  ############################

  validates :name,
            presence: true,
            length: { maximum: 255 }

  validates :fingerprint,
            presence: true,
            length: { maximum: 255 }

  validates :key_type,
            presence: true,
            inclusion: { in: ["ssh", "x509"], message: "%{value} is not a valid type" }

  validates :user,
            presence: true

  ####################################
  #
  # Attributes
  #
  ####################################

  attr_accessor :name, :fingerprint, :key_type, :private_key, :public_key, :user

  ############################
  #
  # Public Instance Methods
  #
  ############################

  def initialize(user:, name: nil, fingerprint: nil, key_type: "ssh", public_key: nil, private_key: nil)
    @user = user
    @name = name
    @fingerprint = fingerprint
    @key_type = key_type
    @public_key = public_key
    @private_key = private_key
  end
end

app/controllers/key_pairs_controller.rb
#==============================================================================
# Copyright (C) 2024-present Alces Flight Ltd.
#
# This file is part of Concertim Visualisation App.
#
# This program and the accompanying materials are made available under
# the terms of the Eclipse Public License 2.0 which is available at
# <https://www.eclipse.org/legal/epl-2.0>, or alternative license
# terms made available by Alces Flight Ltd - please direct inquiries
# about licensing to licensing@alces-flight.com.
#
# Concertim Visualisation App is distributed in the hope that it will be useful, but
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR
# IMPLIED INCLUDING, WITHOUT LIMITATION, ANY WARRANTIES OR CONDITIONS
# OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A
# PARTICULAR PURPOSE. See the Eclipse Public License 2.0 for more
# details.
#
# You should have received a copy of the Eclipse Public License 2.0
# along with Concertim Visualisation App. If not, see:
#
#  https://opensource.org/licenses/EPL-2.0
#
# For more information on Concertim Visualisation App, please visit:
# https://github.com/openflighthpc/concertim-ct-visualisation-app
#==============================================================================

class KeyPairsController < ApplicationController
  before_action :set_project_id, except: :new

  def new
    @user = current_user
    @key_pair = KeyPair.new(user: @user)
    authorize! :create, @key_pair
    @cloud_service_config = CloudServiceConfig.first
    if @cloud_service_config.nil?
      flash[:alert] = "Unable to create key-pairs: cloud environment config not set"
      redirect_to root_path
    end
  end

  def index
    @cloud_service_config = CloudServiceConfig.first
    if @cloud_service_config.nil?
       flash[:alert] = "Unable to check key-pairs: cloud environment config not set. Please contact an admin"
       redirect_to edit_user_registration_path
       return
    end

    unless @project_id
      flash[:alert] = "Unable to check key-pairs: you must belong to a team with a project id."
      redirect_to edit_user_registration_path
      return
    end

    result = GetUserKeyPairsJob.perform_now(@cloud_service_config, current_user, @project_id)
    if result.success?
      @key_pairs = result.key_pairs
    else
      flash[:alert] = "Unable to get key-pairs: #{result.error_message}"
      redirect_to edit_user_registration_path
    end
  end

  def create
    @cloud_service_config = CloudServiceConfig.first
    @user = current_user
    public_key = key_pair_params[:public_key].blank? ? nil : key_pair_params[:public_key]
    @key_pair = KeyPair.new(user: @user, name: key_pair_params[:name], key_type: key_pair_params[:key_type],
                                                public_key: public_key)
    authorize! :create, @key_pair

    if @cloud_service_config.nil?
      flash[:alert] = "Unable to send key-pair requests: cloud environment config not set. Please contact an admin"
      redirect_to edit_user_registration_path
      return
    end

    unless @project_id
      flash[:alert] = "Unable to create key-pair: you must belong to a team with a project id."
      redirect_to edit_user_registration_path
      return
    end

    result = CreateKeyPairJob.perform_now(@key_pair, @cloud_service_config, current_user, @project_id)

    if result.success?
      render action: :success
    else
      flash[:alert] = result.error_message
      redirect_to key_pairs_path
    end
  end

  def destroy
    authorize! :destroy, KeyPair.new(user: current_user)
    @cloud_service_config = CloudServiceConfig.first
    @user = current_user
    if @cloud_service_config.nil?
      flash[:alert] = "Unable to send key-pair requests: cloud environment config not set. Please contact an admin"
      redirect_to edit_user_registration_path
      return
    end

    unless @project_id
      flash[:alert] = "Unable to send key-pair deletion request: you must belong to a team with a project id."
      redirect_to edit_user_registration_path
      return
    end

    result = DeleteKeyPairJob.perform_now(params[:name], @cloud_service_config, current_user, @project_id)

    if result.success?
      flash[:success] = "Key-pair '#{params[:name]}' deleted"
    else
      flash[:alert] = result.error_message
    end
    redirect_to key_pairs_path
  end

  private

  PERMITTED_PARAMS = %w[name key_type public_key]
  def key_pair_params
    params.require(:key_pair).permit(*PERMITTED_PARAMS)
  end

  # key pairs are user (not project) specific, but membership of a project is required
  # to view, create and delete them
  def set_project_id
    @project_id = current_user.teams.where.not(project_id: nil).where(deleted_at: nil).first&.project_id
  end
end

app/views/key_pairs/_form.html.erb
<%= form_for(@key_pair, url: key_pairs_path) do |f| %>

  <% if @key_pair.errors.any? %>
    <div id="error_explanation">
      <h2>There <%= "#{@key_pair.errors.count == 1 ? 'is' : 'are'}" %> <%= pluralize(@key_pair.errors.count, "error") %>:</h2>
   
      <ul>
      <% @key_pair.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="formItem">
    <%= f.label :name, "Key name", class: 'required_field' %>
    <%= f.text_field :name, autocomplete: :off, pattern: "^[a-zA-Z][a-zA-Z0-9\\-_]*$", required: true %>
  </div>

  <div class="formItem">
    <%= f.label :key_type, "Key type", class: 'required_field' %>
    <%= f.select :key_type, [["SSH Key", "ssh"]], required: true %>
  </div>

  <div class="formItem">
    <%= f.label :public_key, "Public key (optional)" %>
    <input type="file" id="public-key-input">

    <%= f.text_area :public_key, id: 'public_key_field' %>
  </div>

  <%= f.submit 'Create' %>
<% end %>

app/views/key_pairs/index.html.erb
<% set_title 'Your key-pairs' -%>

<% if @key_pairs.any? %>
  <h4>Current key-pairs</h4>

  <table>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Fingerprint</th>
    </tr>
    <% @key_pairs.each do |key_pair| %>
      <tr>
        <td><%= key_pair.name %></td>
        <td><%= key_pair.key_type %></td>
        <td><%= key_pair.fingerprint %></td>
        <td>
          <%= form_for(key_pair, url: delete_key_pairs_path(name: key_pair.name), method: :delete,
                       html: {class: "delete-key-pair-form",
                       onsubmit: "return confirm('Are you sure you want to delete #{key_pair.name}? This cannot be undone.')"}) do |f| %>
            <%= f.submit 'Delete' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
<% else %>
  <p>
    You currently have no key-pairs.
  </p>
<% end %>

<div>
  <a href=<%= new_key_pair_path %> class="button">+ Create new key-pair</a>
</div>

app/views/key_pairs/new.html.erb
<% content_for(:head) do %>
  <%= javascript_import_module_tag "key_pairs/new" %>
<% end %>

<%
  set_title 'New key-pair'
-%>
<%= render 'form' %>

app/views/key_pairs/success.html.erb
<% set_title 'Key-pair created' -%>

<% if @key_pair.private_key %>
  <h5>
    Please ensure you make a copy of the private key, as you will not be able to retrieve it after leaving
  this page.
  </h5>
<% end %>

<%= form_for(@key_pair, url: '') do |f| %>
  <div class="formItem">
    <%= f.label :name, "Key name", class: 'required_field' %>
    <%= f.text_field :name, disabled: true %>
  </div>

  <div class="formItem">
    <%= f.label :key_type, "Key type" %>
    <%= f.select :key_type, [["SSH Key", "ssh_key"], ["X509 Certificate", "x509"]], {}, {disabled: true} %>
  </div>

  <div class="formItem">
    <%= f.label :fingerprint, "Fingerprint" %>
    <%= f.text_field :fingerprint, disabled: true %>
  </div>


  <% if @key_pair.private_key %>
    <div class="formItem">
      <%= f.label :private_key, "Private key" %>
      <%= f.text_area :private_key, disabled: true %>
    </div>
    <div class="button small copyToClipboard" data-text="<%= @key_pair.private_key %>">Copy</div>
  <% end %>

  <% if @key_pair.public_key %>
    <div class="formItem">
      <%= f.label :public_key, "Public key" %>
      <%= f.text_area :public_key, disabled: true %>
    </div>
  <% end %>
<% end %>